<div class="modal fade mobilePaymentModal momo" tabindex="-1" role="dialog" aria-labelledby="mobilePaymentModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="lable-payment">MoMo - Mã QR Code</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-5">
                        <img style="position: relative;display: block; margin: 0 auto" src="" atl="QrCode" class="qr-img">
                        <p class="time-countdown"></p>
                    </div>
                    <div class="col-xs-7">
                        <dl>
                            <dt>Thực hiện theo hướng dẫn sau để thanh toán:</dt>
                            <br>
                            <dd>Bước 1: Đăng Nhập App MoMo</dd>
                            <dd>Bước 2: Bấm Chọn icon <span class="glyphicon glyphicon-qrcode"></span> góc phải trên cùng và tiến hành quét QR Code.</dd>
                            <dd>Bước 3: Bấm chọn Xác Nhận trên Ví và hoàn tất.</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a class="bt-repayment btn btn-default" href="https://tiki.vn/?_lc=Vk4wMzQwMjIwMDk%3D" role="button" onclick="if (window.dataLayer) {dataLayer.push({pagetype: 'payment', event: 'momo_choice_other_payment'});}">Chọn hình thức thanh toán khác</a>
            </div>
        </div>
    </div>
</div>